"""Runs every test set in test_data/ and prints PASS / FAIL.  Start with:  python run_tests.py

The expected result of every test is stored in test_data/expected.json (same IDs as the test plan).
"""
import io
import json
from pathlib import Path

import openpyxl

from logic import Settings, check_plan, improve, kpis, read_distances, read_plan, read_timetable, to_excel

HERE = Path(__file__).parent
DATA, TESTS = HERE / "data", HERE / "test_data"


def path(name):
    if "(original)" in name:
        return DATA / "Bus_Planning.xlsx"
    return TESTS / name if (TESTS / name).exists() else DATA / name


def run(test):
    """Returns a list of problems; an empty list means the test passed."""
    s = Settings(use_file_energy=test["energy_source"] == "file", start_soc=test.get("start_soc") or 0.9)
    dist, timetable = read_distances(DATA / "DistanceMatrix.xlsx"), read_timetable(path(test["timetable"]))

    if test["id"] == "GEN-2":                       # export of a generated plan has the client's format
        ours = openpyxl.load_workbook(io.BytesIO(to_excel(improve(timetable, dist, s)))).active
        client = openpyxl.load_workbook(DATA / "Bus_Planning.xlsx").active
        same = [c.value for c in ours[1]] == [c.value for c in client[1]] and ours.title == client.title
        return [] if same else ["export format differs from the client's file"]

    if test["id"] == "GEN-1":                       # plan generated by the tool itself
        plan, issues = improve(timetable, dist, s), []
    else:
        plan, issues = read_plan(path(test["file"]), dist)
    timeline = None
    if plan is not None:
        timeline, more = check_plan(plan, timetable, dist, s)
        issues += more
    problems = []
    for check, severity, row, bus in test["must"]:
        if not any(i["check"] == check and i["severity"] == severity and row in (None, i["row"]) and bus in (None, i["bus"])
                   for i in issues):
            problems.append(f"expected {severity} {check}" + (f" row {row}" if row else "") + (f" bus {bus}" if bus else ""))
    for check in test["must_not"]:
        if any(i["check"] == check and i["severity"] == "error" for i in issues):
            problems.append(f"unexpected error {check}")
    if test["id"] == "GEN-1" and kpis(timeline)["Buses used"] >= 20:
        problems.append("generated plan does not use fewer buses than the original (20)")
    for name, value in test["kpi"].items():
        if kpis(timeline).get(name) != value:
            problems.append(f"{name} = {kpis(timeline).get(name)}, expected {value}")
    if test.get("energy_check"):
        e = test["energy_check"]
        energy = timeline[(timeline.bus == e["bus"]) & (timeline.start == e["start"])].energy.iloc[0]
        if abs(energy - e["value"]) > 1e-6:
            problems.append(f"energy {energy:.4f}, expected {e['value']}")
    return problems


if __name__ == "__main__":
    tests = json.loads((TESTS / "expected.json").read_text())
    failed = 0
    for test in tests:
        problems = run(test)
        failed += bool(problems)
        print(f"{'PASS' if not problems else 'FAIL'}  {test['id']:<8} {test['what']}" + (f"  -> {problems}" if problems else ""))
    print(f"\n{len(tests) - failed} of {len(tests)} tests passed")
